### ISSUE TITLE
problem when compiling theONE

### ISSUE THREAD

**Issue by MGS88** [akeranen/the-one#30]
Hi there
I when I try to run the ONE version 1.6.0 with dLife routing scheme I get this error and that happen for long time but now I really need that routing, though I did follow the readme file but I skip the Bubble RAP because I couldn't find it.
the error is shown before I even run the simulator and when I run it I get this in the console:
`Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	The method initialize(DTNHost, List<MessageListener>) is undefined for the type MessageRouter

	at core.DTNHost.setRouter(DTNHost.java:121)
	at core.DTNHost.<init>(DTNHost.java:78)
	at core.SimScenario.createHosts(SimScenario.java:425)
	at core.SimScenario.<init>(SimScenario.java:171)
	at core.SimScenario.getInstance(SimScenario.java:183)
	at ui.DTNSimUI.initModel(DTNSimUI.java:93)
	at ui.DTNSimUI.start(DTNSimUI.java:76)
	at core.DTNSim.main(DTNSim.java:135)
`

**Comment by MGS88** [comment]
find out that there is no need to implement Bubble RAP, and only use dlife.txt in sample folder as a setting instead of default_settings.txt
and that was used with 1.4.1 version
