### ISSUE TITLE
1.8JDK Can not run the one.Already compile

### ISSUE THREAD

**Issue by DreaBettJ** [akeranen/the-one#85]
the exception:

Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/local/java/jdk1.8.0_152/jre/lib/amd64/libawt_xawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at java.awt.Toolkit$3.run(Toolkit.java:1636)
	at java.awt.Toolkit$3.run(Toolkit.java:1634)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1668)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at gui.DTNSimGUI.startGUI(DTNSimGUI.java:38)
	at gui.DTNSimGUI.runSim(DTNSimGUI.java:101)
	at ui.DTNSimUI.start(DTNSimUI.java:77)
	at core.DTNSim.main(DTNSim.java:92)

**Comment by aliali787** [comment]
C:\the-one-1.6.0>javac -extdirs lib/ report/*.java
'javac' is not recognized as an internal or external command,
operable program or batch file.

C:\the-one-1.6.0>javac -extdirs lib/ routing/*.java
'javac' is not recognized as an internal or external command,
operable program or batch file.

C:\the-one-1.6.0>javac -extdirs lib/ gui/*.java
'javac' is not recognized as an internal or external command,
operable program or batch file.

C:\the-one-1.6.0>javac -extdirs lib/ input/*.java
'javac' is not recognized as an internal or external command,
operable program or batch file.

C:\the-one-1.6.0>javac -extdirs lib/ applications/*.java
'javac' is not recognized as an internal or external command,
operable program or batch file.

C:\the-one-1.6.0>javac -extdirs lib/ interfaces/*.java
'javac' is not recognized as an internal or external command,
operable program or batch file.

C:\the-one-1.6.0>one.bat

C:\the-one-1.6.0>java -Xmx512M -cp .;lib/ECLA.jar;lib/DTNConsoleConnection.jar core.DTNSim
Error: Could not find or load main class core.DTNSim

C:\the-one-1.6.0>

**Comment by Miloyym** [comment]
@aliali787 Your JDK was not successfully installed. Or check the system variables, make sure that you have already configured `%JAVA_HOME%` path and add it into `Path`.

**Comment by DreaBettJ** [comment]
thank&nbsp;you,my&nbsp;question&nbsp;already&nbsp;is&nbsp;solved。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Miloyym"<notifications@github.com&gt;; 
发送时间: 2020年8月4日(星期二) 上午10:05
收件人: "akeranen/the-one"<the-one@noreply.github.com&gt;; 
抄送: "jo妮jo斯达"<2293785363@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [akeranen/the-one] 1.8JDK Can not run the one.Already compile (#85)





 
@aliali787 Your JDK was not successfully installed. Or check the system variables, make sure that you have already configured %JAVA_HOME% path and add it into Path.
